on: 
  push:
    tags:
    - '*'
    
jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    uses: ncipollo/release-action@v1.12.0
    with:
      allowUpdates: true
      artifacts: "release.tar.gz"
